export const district = [
  {
    id: 1,
    pid: 0,
    district_name: '中国',
    type: 0,
    hierarchy: 1,
    district_sqe: '.1.',
  },
  {
    id: 2,
    pid: 1,
    district_name: '北京',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.2.',
  },
  {
    id: 3,
    pid: 1,
    district_name: '安徽',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.3.',
  },
  {
    id: 4,
    pid: 1,
    district_name: '福建',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.4.',
  },
  {
    id: 5,
    pid: 1,
    district_name: '甘肃',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.5.',
  },
  {
    id: 6,
    pid: 1,
    district_name: '广东',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.6.',
  },
  {
    id: 7,
    pid: 1,
    district_name: '广西',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.7.',
  },
  {
    id: 8,
    pid: 1,
    district_name: '贵州',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.8.',
  },
  {
    id: 9,
    pid: 1,
    district_name: '海南',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.9.',
  },
  {
    id: 10,
    pid: 1,
    district_name: '河北',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.10.',
  },
  {
    id: 11,
    pid: 1,
    district_name: '河南',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.11.',
  },
  {
    id: 12,
    pid: 1,
    district_name: '黑龙江',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.12.',
  },
  {
    id: 13,
    pid: 1,
    district_name: '湖北',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.13.',
  },
  {
    id: 14,
    pid: 1,
    district_name: '湖南',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.14.',
  },
  {
    id: 15,
    pid: 1,
    district_name: '吉林',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.15.',
  },
  {
    id: 16,
    pid: 1,
    district_name: '江苏',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.16.',
  },
  {
    id: 17,
    pid: 1,
    district_name: '江西',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.17.',
  },
  {
    id: 18,
    pid: 1,
    district_name: '辽宁',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.18.',
  },
  {
    id: 19,
    pid: 1,
    district_name: '内蒙古',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.19.',
  },
  {
    id: 20,
    pid: 1,
    district_name: '宁夏',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.20.',
  },
  {
    id: 21,
    pid: 1,
    district_name: '青海',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.21.',
  },
  {
    id: 22,
    pid: 1,
    district_name: '山东',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.22.',
  },
  {
    id: 23,
    pid: 1,
    district_name: '山西',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.23.',
  },
  {
    id: 24,
    pid: 1,
    district_name: '陕西',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.24.',
  },
  {
    id: 25,
    pid: 1,
    district_name: '上海',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.25.',
  },
  {
    id: 26,
    pid: 1,
    district_name: '四川',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.26.',
  },
  {
    id: 27,
    pid: 1,
    district_name: '天津',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.27.',
  },
  {
    id: 28,
    pid: 1,
    district_name: '西藏',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.28.',
  },
  {
    id: 29,
    pid: 1,
    district_name: '新疆',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.29.',
  },
  {
    id: 30,
    pid: 1,
    district_name: '云南',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.30.',
  },
  {
    id: 31,
    pid: 1,
    district_name: '浙江',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.31.',
  },
  {
    id: 32,
    pid: 1,
    district_name: '重庆',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.32.',
  },
  {
    id: 33,
    pid: 1,
    district_name: '香港',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.33.',
  },
  {
    id: 34,
    pid: 1,
    district_name: '澳门',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.34.',
  },
  {
    id: 35,
    pid: 1,
    district_name: '台湾',
    type: 1,
    hierarchy: 2,
    district_sqe: '.1.35.',
  },
  {
    id: 36,
    pid: 3,
    district_name: '安庆',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.36.',
  },
  {
    id: 37,
    pid: 3,
    district_name: '蚌埠',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.37.',
  },
  {
    id: 38,
    pid: 3,
    district_name: '巢湖',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.38.',
  },
  {
    id: 39,
    pid: 3,
    district_name: '池州',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.39.',
  },
  {
    id: 40,
    pid: 3,
    district_name: '滁州',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.40.',
  },
  {
    id: 41,
    pid: 3,
    district_name: '阜阳',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.41.',
  },
  {
    id: 42,
    pid: 3,
    district_name: '淮北',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.42.',
  },
  {
    id: 43,
    pid: 3,
    district_name: '淮南',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.43.',
  },
  {
    id: 44,
    pid: 3,
    district_name: '黄山',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.44.',
  },
  {
    id: 45,
    pid: 3,
    district_name: '六安',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.45.',
  },
  {
    id: 46,
    pid: 3,
    district_name: '马鞍山',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.46.',
  },
  {
    id: 47,
    pid: 3,
    district_name: '宿州',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.47.',
  },
  {
    id: 48,
    pid: 3,
    district_name: '铜陵',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.48.',
  },
  {
    id: 49,
    pid: 3,
    district_name: '芜湖',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.49.',
  },
  {
    id: 50,
    pid: 3,
    district_name: '宣城',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.50.',
  },
  {
    id: 51,
    pid: 3,
    district_name: '亳州',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.3.51.',
  },
  {
    id: 52,
    pid: 2,
    district_name: '市辖区',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.2.52.',
  },
  {
    id: 53,
    pid: 4,
    district_name: '福州',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.4.53.',
  },
  {
    id: 54,
    pid: 4,
    district_name: '龙岩',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.4.54.',
  },
  {
    id: 55,
    pid: 4,
    district_name: '南平',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.4.55.',
  },
  {
    id: 56,
    pid: 4,
    district_name: '宁德',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.4.56.',
  },
  {
    id: 57,
    pid: 4,
    district_name: '莆田',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.4.57.',
  },
  {
    id: 58,
    pid: 4,
    district_name: '泉州',
    type: 2,
    hierarchy: 3,
    district_sqe: '.1.4.58.',
  },
];
